version: "2.1"

services:
  bukk:
    container_name: bukk
    restart: always
    image: bukk
    build: .
    # environment:
    #   NODE_ENV: production
    ports:
      - 4000:4000
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
